[package]
name = "c_string"
version = "0.1.0"
edition = "2021"

[lib]
name = "c_string"
path = "src/lib.rs"
crate-type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
libc = "0.2"
