[package]
name = "algorithm"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "algorithm"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
recess_algorithm = { path = "../../../rust/recess_algorithm" }
log = "0.4.0"
env_logger = "0.9.1"

itertools = "0.10.4"
